#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NZWeatherApp.Resource", IsApplication=true)]

namespace NZWeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int place_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080013
			public const int FullText = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int GetWeatherbtn = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int Image = 2131230746;
			
			// aapt resource value: 0x7f080015
			public const int btnGPS = 2131230741;
			
			// aapt resource value: 0x7f080007
			public const int btnGetGPSWeather = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int btnLocalWeather = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int condSection = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int humiditSection = 2131230736;
			
			// aapt resource value: 0x7f080003
			public const int latSection = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int linearLayout1 = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int locSection = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int longSection = 2131230720;
			
			// aapt resource value: 0x7f080012
			public const int scrollView1 = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int spCity = 2131230743;
			
			// aapt resource value: 0x7f08000e
			public const int tempSection = 2131230734;
			
			// aapt resource value: 0x7f08001b
			public const int tvAllText = 2131230747;
			
			// aapt resource value: 0x7f08000d
			public const int tvConditionslbl = 2131230733;
			
			// aapt resource value: 0x7f080016
			public const int tvCurrentWeather = 2131230742;
			
			// aapt resource value: 0x7f080011
			public const int tvHumiditylbl = 2131230737;
			
			// aapt resource value: 0x7f080004
			public const int tvLatlbl = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int tvLocationlbl = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int tvLonglbl = 2131230721;
			
			// aapt resource value: 0x7f080019
			public const int tvTempChange = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int tvTemperature = 2131230744;
			
			// aapt resource value: 0x7f08000f
			public const int tvTemplbl = 2131230735;
			
			// aapt resource value: 0x7f080005
			public const int txtLat = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int txtLocation = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int txtLong = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GPS = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int place_prompt = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
